export default [
  {
    "id": 1,
    "title": "CEDIRATES",
    "description": "Compare Exchange Rates and Fuel Prices",
    "logo": "/images/cedi.png",
    "skills": ["REACT", 'CSS', 'MUI', 'NODEJS', 'MONGODB'],
    "website": "https://cedirates.com/",
    "github": "https://github.com/eakelvin",
  },
  {
    "id": 2,
    "title": "VILLAGE CREATORS",
    "description": "Celebrate creativity, nurture growth, build community connections",
    "logo": "/images/vc.png",
    "skills": ["NEXT", 'BOOTSTRAP', 'SANITY'],
    "website": "https://www.villagecreators.net/",
    "github": "https://github.com/eakelvin/village-creators-main.git",
  },
  {
    "id": 3,
    "title": "FUNDTALK",
    "description": "Financial GPT || A financial chatbot to answer financial questions",
    "logo": "/images/fundtalk.jpg",
    "logo1": "/images/fundtalk1.jpg",
    "logo2": "/images/fundtalk2.jpg",
    "skills": ["MERN STACK", "OPEN AI API", "BOOTSTRAP"],
    "website": "https://finalfundtalk.onrender.com",
    "github": "https://github.com/BabatundeJimoh/FundTalk.git",
  },
    {
      "id": 4,
      "title": "DEV JOBS",
      "description": "A webapp to help users search for jobs",
      "logo": "/images/dev.jpg",
      "skills": ["REACT", "BOOTSTRAP"],
      "website": "https://devjobs-ea.netlify.app/",
      "github": "https://github.com/eakelvin/DevJobs-Project.git",
    },
    {
      "id": 5,
      "title": "E-COMMERCE",
      "description": "A webapp to help users shop for products",
      "logo": "/images/ecommerce.jpg",
      "skills": ["REACT", "REDUX", "BOOTSTRAP", "FIREBASE"],
      "website": "https://ecommerce-ea.netlify.app/",
      "github": "https://github.com/eakelvin/ecommerce-app.git",
    },
    {
      "id": 6,
      "title": "MAVE SPORTS",
      "description": "A website for sports fans specifically football and basketball",
      "logo": "/images/mave1.jpg",
      "skills": ["WORDPRESS"],
      "website": "https://mavesports.com/",
      "github": "https://mavesports.com/",
    },
    {
      "id": 7,
      "title": "EA TOUR",
      "description": "Explore and discover the best tourism content in Ghana",
      "logo": "/images/tour.jpg",
      "skills": ["HTML", "CSS", "JavaScript", "BOOTSTRAP"],
      "website": "https://tour-ea.netlify.app/",
      "github": "https://github.com/eakelvin/EA-Tour.git",
    },
    {
      "id": 8,
      "title": "API PROJECTS",
      "description": "A collection of different web apps that utilize APIs",
      "logo": "/images/API.jpg",
      "skills": ["HTML", "VANILLA CSS", "JAVASCRIPT", "REST API"],
      "website": "https://api-app-ea.netlify.app/",
      "github": "https://github.com/eakelvin/Api-projects.git",
    },
    {
      "id": 9,
      "title": "TERMINAL CHATBOT",
      "description": "A chatbot to communicate with an AI in the terminal",
      "logo": "/images/terminal.jpg",
      "skills": ["NODE JS", "JAVASCRIPT", "API"],
      "website": "",
      "github": "https://github.com/eakelvin/terminal-chatbot.git",
    },
    {
      "id": 10,
      "title": "PERSONAL BLOG",
      "description": "A website where I share my thoughts, ideas and experiences",
      "logo": "/images/blog.jpg",
      "skills": ["HTML", "CSS", "NODE JS", "MONDODB", "EXPRESS JS"],
      "website": "https://ea-blog.onrender.com/",
      "github": "https://github.com/eakelvin/blog.git",
    },
    {
      "id": 11,
      "title": "LIVE CHAT",
      "description": "A webapp to helps users communicate with eachother",
      "logo": "/images/livechat1.jpg",
      "logo2": "/images/livechat2.jpg",
      "skills": ["MERN STACK", "SOCKET-IO", "TAILWIND"],
      "website": "",
      "github": "https://github.com/eakelvin/livechat.git",
    },
      {
      "id": 12,
      "title": "COUNTRY APP",
      "description": "A website that contains details of all countries in the world",
      "logo": "/images/country-app.jpg",
      "skills": ["API", "TAILWIND CSS", "REACT"],
      "website": "https://countries-app-ea.netlify.app/",
      "github": "https://github.com/eakelvin/countries-app.git",
    },
    {
      "id": 13,
      "title": "MEME GENERATOR",
      "description": "Generate random memes",
      "logo": "/images/meme.jpeg",
      "skills": ["REACT", "CSS", "API"],
      "website": "https://memegenerator-ea.netlify.app/",
      "github": "https://github.com/eakelvin/Meme-Generator.git",
    },
    {
      "id": 14,
      "title": "TENZIES GAME",
      "description": "Play a game of rolling dice until all the dice are the same",
      "logo": "/images/tenzies.jpeg",
      "skills": ["REACT", "CSS"],
      "website": "https://tenzies-game-ea.netlify.app/",
      "github": "https://github.com/eakelvin/tenzies-game.git",
    },
    {
      "id": 15,
      "title": "MULTI STEP FORM",
      "description": "Gathers data and proposes a sample JSON object",
      "logo": "/images/multistep.png",
      "skills": ["NEXTJS", "TYPESCRIPT", "TAILWIND"],
      "website": "https://ea-form.netlify.app/",
      "github": "https://github.com/eakelvin/form-test.git",
    },
    {
      "id": 16,
      "title": "NOTES APP",
      "description": "Write your notes on this web app",
      "logo": "/images/note.jpeg",
      "skills": ["TAILWIND", "REACT", "REDUX"],
      "website": "https://notetaker-ea.netlify.app/",
      "github": "https://github.com/eakelvin/note-app.git",
    },
    {
      "id": 17,
      "title": "EXPENSE TRACKER",
      "description": "Keep track of your expenses",
      "logo": "/images/exp.jpeg",
      "skills": ["TAILWIND", "REACT", "REDUX"],
      "website": "https://expensetracker-ea.netlify.app/",
      "github": "https://github.com/eakelvin/expense-tracker.git",
    },
    {
      "id": 18,
      "title": "SPIN THE BOTTLE GAME",
      "description": "Spin the bottle to generate a random dare",
      "logo": "/images/spin.jpeg",
      "skills": ["TAILWIND CSS", "JAVASCRIPT", "REST API"],
      "website": "https://spinthebottleklm.netlify.app/",
      "github": "https://github.com/blameleo/spin-the-bottle.git",
    },
    {
      "id": 19,
      "title": "MY MED",
      "description": "Control your medication schedule, update medical details and set reminders",
      "logo": "/images/med.png",
      "skills": ["TAILWIND CSS", "MERN STACK"],
      "website": "https://my-med-web-fabe.vercel.app/",
      "github": "https://github.com/eakelvin/my-med-web.git",
    },
    // {
    //   "id": 20,
    //   "title": "",
    //   "description": "",
    //   "logo": "/images/tenzies.jpeg",
    //   "skills": ["REACT", "CSS"],
    //   "website": "",
    //   "github": "",
    // },  
]